# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='index.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bindex.proto\x12\x05proto\"~\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x12*\n\x07records\x18\x03 \x03(\x0b\x32\x19.proto.Field.RecordsEntry\x1a.\n\x0cRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"z\n\x05Index\x12\x30\n\nembeddings\x18\x01 \x03(\x0b\x32\x1c.proto.Index.EmbeddingsEntry\x1a?\n\x0f\x45mbeddingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.proto.Field:\x02\x38\x01\x62\x06proto3'
)




_FIELD_RECORDSENTRY = _descriptor.Descriptor(
  name='RecordsEntry',
  full_name='proto.Field.RecordsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Field.RecordsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Field.RecordsEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=148,
)

_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='proto.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='proto.Field.dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='records', full_name='proto.Field.records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FIELD_RECORDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=148,
)


_INDEX_EMBEDDINGSENTRY = _descriptor.Descriptor(
  name='EmbeddingsEntry',
  full_name='proto.Index.EmbeddingsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Index.EmbeddingsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Index.EmbeddingsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=272,
)

_INDEX = _descriptor.Descriptor(
  name='Index',
  full_name='proto.Index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='embeddings', full_name='proto.Index.embeddings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INDEX_EMBEDDINGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=272,
)

_FIELD_RECORDSENTRY.containing_type = _FIELD
_FIELD.fields_by_name['records'].message_type = _FIELD_RECORDSENTRY
_INDEX_EMBEDDINGSENTRY.fields_by_name['value'].message_type = _FIELD
_INDEX_EMBEDDINGSENTRY.containing_type = _INDEX
_INDEX.fields_by_name['embeddings'].message_type = _INDEX_EMBEDDINGSENTRY
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['Index'] = _INDEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {

  'RecordsEntry' : _reflection.GeneratedProtocolMessageType('RecordsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FIELD_RECORDSENTRY,
    '__module__' : 'index_pb2'
    # @@protoc_insertion_point(class_scope:proto.Field.RecordsEntry)
    })
  ,
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'index_pb2'
  # @@protoc_insertion_point(class_scope:proto.Field)
  })
_sym_db.RegisterMessage(Field)
_sym_db.RegisterMessage(Field.RecordsEntry)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {

  'EmbeddingsEntry' : _reflection.GeneratedProtocolMessageType('EmbeddingsEntry', (_message.Message,), {
    'DESCRIPTOR' : _INDEX_EMBEDDINGSENTRY,
    '__module__' : 'index_pb2'
    # @@protoc_insertion_point(class_scope:proto.Index.EmbeddingsEntry)
    })
  ,
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'index_pb2'
  # @@protoc_insertion_point(class_scope:proto.Index)
  })
_sym_db.RegisterMessage(Index)
_sym_db.RegisterMessage(Index.EmbeddingsEntry)


_FIELD_RECORDSENTRY._options = None
_INDEX_EMBEDDINGSENTRY._options = None
# @@protoc_insertion_point(module_scope)
